[features]
seeds = false
skip-lint = false

[programs.localnet]
neet_clearing_house = "EdqgHXeGhpBqp2MrshF3PVpBe6D2s7g8UYALy9MHLzww"
neet_amm            = "6jAsJnMMFEP1j8yN7T578Th9qv4886w7dEsP4wmkwmkc"
neet_oracle_adapter = "DLCNVQMwyFEr6WgzKYScXc7PZs3xfLEwPehYer7LSAUe"
neet_funding        = "H9T4E6E2nqVMqGh8M5hbW3kHHxJ66SjnDkTaZgnm3CJ"
neet_liquidation    = "Bosr1Ah36SiY8jESXRbYXAXUDbm1kGGV8VQ9j8Apx5KQ"
neet_insurance      = "bMfcXaB9aqYJFYBexVUBTsqAAMUmmChur2jt4NpHNJr"
neet_treasury       = "9Sq1nXNFt2uFvZNNxBnCCgT2P1s7HDdewJnBiuQxQuYQ"

[programs.devnet]
neet_clearing_house = "EdqgHXeGhpBqp2MrshF3PVpBe6D2s7g8UYALy9MHLzww"
neet_amm            = "6jAsJnMMFEP1j8yN7T578Th9qv4886w7dEsP4wmkwmkc"
neet_oracle_adapter = "DLCNVQMwyFEr6WgzKYScXc7PZs3xfLEwPehYer7LSAUe"
neet_funding        = "H9T4E6E2nqVMqGh8M5hbW3kHHxJ66SjnDkTaZgnm3CJ"
neet_liquidation    = "Bosr1Ah36SiY8jESXRbYXAXUDbm1kGGV8VQ9j8Apx5KQ"
neet_insurance      = "bMfcXaB9aqYJFYBexVUBTsqAAMUmmChur2jt4NpHNJr"
neet_treasury       = "9Sq1nXNFt2uFvZNNxBnCCgT2P1s7HDdewJnBiuQxQuYQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

# Deploy wallet (admin): 4NqMPyuybfgHaWak59psEBx1BzehLp7Po42Za6vmNgGm
# Set DEPLOY_KEYPAIR GitHub secret with the JSON array from SECRETS.md
